### ISSUE TITLE
Stage-switching error

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#372]
So far, we've only seen this happen once, but we wanted to note this here as something to keep an eye on because it seems like something related to glupyter that could happen again.

After restarting solara, I clicked onto Stage 4, and then quickly clicked onto Stage 6. This error cropped up:
```
Traceback (most recent call last):
  File "/Users/Pat/anaconda3/envs/solara/lib/python3.11/site-packages/reacton/core.py", line 1707, in _render
    root_element = el.component.f(*el.args, **el.kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/Documents/GitHub/hubbleds/src/hubbleds/pages/06-prodata/__init__.py", line 64, in Page
    gjapp, viewer = cast(JupyterApplication, solara.use_memo(glue_setup,[]))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/anaconda3/envs/solara/lib/python3.11/site-packages/reacton/core.py", line 879, in use_memo
    return rc.use_memo(f, dependencies, debug_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/anaconda3/envs/solara/lib/python3.11/site-packages/reacton/core.py", line 1244, in use_memo
    value = f()
            ^^^
  File "/Users/Pat/Documents/GitHub/hubbleds/src/hubbleds/pages/06-prodata/__init__.py", line 59, in glue_setup
    viewer = gjapp.new_data_viewer(HubbleFitView, show=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/anaconda3/envs/solara/lib/python3.11/site-packages/glue_jupyter/app.py", line 189, in new_data_viewer
    viewer = super().new_data_viewer(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/anaconda3/envs/solara/lib/python3.11/site-packages/glue/core/application_base.py", line 81, in new_data_viewer
    c = viewer_class(self._session)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/Documents/GitHub/cosmicds/src/cosmicds/viewers/viewer.py", line 24, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/Pat/anaconda3/envs/solara/lib/python3.11/site-packages/glue_plotly/viewers/scatter/viewer.py", line 36, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/Pat/anaconda3/envs/solara/lib/python3.11/site-packages/glue_plotly/viewers/common/viewer.py", line 37, in __init__
    super(PlotlyBaseView, self).__init__(session, state=state)
  File "/Users/Pat/anaconda3/envs/solara/lib/python3.11/site-packages/glue_jupyter/view.py", line 37, in __init__
    if self.session.application.get_setting('disable_output_widget')
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/anaconda3/envs/solara/lib/python3.11/site-packages/glue/core/application_base.py", line 168, in get_setting
    return self._settings[key][0]
           ~~~~~~~~~~~~~~^^^^^
KeyError: 'disable_output_widget'
```

**Comment by Carifio24** [comment]
Just a note that the relevant setting should be defined by the glue-jupyter application [here](https://github.com/glue-viz/glue-jupyter/blob/main/glue_jupyter/app.py#L68).
