### ISSUE TITLE
Stage 4 Hubble Slideshow error

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#514]
I'm not sure what triggered this or how often this might crop up, but I was working on Stage 4, and at some point, when I clicked the button to open the Hubble Slideshow, it wouldn't appear.

This was in the console:
```
Uncaught (in promise) Error: DOM element provided is null or undefined
    at Object.getGraphDiv (plotly-2.32.0.min.js:8:338854)
    at e.newPlot (plotly-2.32.0.min.js:8:436663)
    at VueComponent.mounted (eval at <anonymous> (VueTemplateRenderer.js:351:21), <anonymous>:32:12)
```

There were no terminal errors.

Refreshing the browser fixed the issue.

**Comment by patudom** [comment]
Closing because I haven't seen this crop up recently.
