### ISSUE TITLE
Student galaxy measurements are not appearing in table anymore

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#515]
After merging in #513, my student's data table is not getting populated with my velocity & distance measurements (but they are still in the db). Student 4864 if that helps.

This is from Stage 4.
<img width="801" alt="Screenshot 2024-07-22 at 10 14 56 PM" src="https://github.com/user-attachments/assets/90fb9f98-eb2d-4e5a-bf89-cf1dd0d759bd">

**Comment by patudom** [comment]
I just tried reloading and I couldn't even get to Stage 4. There were a gazillion logger messages that scrolled through my terminal and this appears over and over:
```
Traceback (most recent call last):
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/reacton/core.py", line 1707, in _render
    root_element = el.component.f(*el.args, **el.kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/Documents/GitHub/hubbleds/src/hubbleds/pages/04-explore-data/__init__.py", line 57, in Page
    solara.lab.use_task(_load_component_state)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/solara/tasks.py", line 846, in use_task
    return wrapper(f)
           ^^^^^^^^^^
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/solara/tasks.py", line 840, in wrapper
    raise task_instance.exception
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/solara/tasks.py", line 259, in runner
    self._last_value = value = await self.function(*args, **kwargs)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/Documents/GitHub/hubbleds/src/hubbleds/pages/04-explore-data/__init__.py", line 51, in _load_component_state
    LOCAL_API.get_stage_state(GLOBAL_STATE, LOCAL_STATE, COMPONENT_STATE)
  File "/Users/Pat/Documents/GitHub/cosmicds/src/cosmicds/remote.py", line 138, in get_stage_state
    component_state.set(component_state.value.__class__(**stage_json))
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/solara/toestand.py", line 358, in set
    self._storage.set(value)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/solara/toestand.py", line 266, in set
    self.fire(value, old)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/solara/toestand.py", line 148, in fire
    with contextlib.ExitStack() as stack:
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/contextlib.py", line 601, in __exit__
    raise exc_details[1]
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/contextlib.py", line 586, in __exit__
    if cb(*exc_details):
       ^^^^^^^^^^^^^^^^
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/reacton/core.py", line 1194, in __exit__
    self._possible_rerender()
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/reacton/core.py", line 1391, in _possible_rerender
    self.render(self.element, self.container)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/reacton/core.py", line 1463, in render
    raise RuntimeError(msg)
RuntimeError: Too many renders triggered, your render loop does not stop
Last reason: Reason: state changed with key auto_subscribe_force_update_counter
Value changed from 63 to 64

Previous reasons: Reason: state changed with key auto_subscribe_force_update_counter
Value changed from 62 to 63
```
